language: scala
dist: trusty
sudo: false
group: beta
env:
  matrix:
    - TRAVIS_SBT_VERSION=0.13.16
    - TRAVIS_SBT_VERSION=1.0.0
script:
- sbt ^^$TRAVIS_SBT_VERSION test
- sbt ^^$TRAVIS_SBT_VERSION scripted
- sbt ^^$TRAVIS_SBT_VERSION publishLocal
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
before_cache:
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/interplay
- find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
notifications:
  slack:
    secure: g1CnQB4HlPTMLYPAaiAA8gV1iI4ezQWHM5auH9UAZXJP+5chmsep9wI2h+Ne3nq5ZfD+gsKIg1ea3FoAxRL7JGUKXOSUJbKmPNc1lePQVyh2eBPPaaYt8ERXrXutmI8pndADxYztRIzzs6oPtRZckcYa7McRZmiRMPGiSLSu2jA=
